# -*- coding: utf-8 -*-
"""PDS CIPAT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tHjlwhaX9OJF_ZBe84ee84WPGB8oKfa
"""

from google.colab import drive

drive.mount('/content/drive')

print(df.shape)
print(df.info())
print(df.describe())

from google.colab import drive
drive.mount('/content/drive')

print(df.isnull().sum())
print(df.duplicated().sum())

import seaborn as sns
import matplotlib.pyplot as plt
sns.countplot(data=df, x="age_group")
plt.title("Patients by Age Group")
plt.show()

print(df["gender"].value_counts())

print(df["department"].value_counts())

print(df["treatment_type"].value_counts())

print(df["visit_type"].value_counts())

print(df["treatment_cost"].mean())
print(df["treatment_cost"].median())
print(df["treatment_cost"].max())
print(df["treatment_cost"].min())

import numpy as np

cost = df["treatment_cost"]

print("Average Cost:", np.mean(cost))
print("Minimum Cost:", np.min(cost))
print("Maximum Cost:", np.max(cost))

print(df["length_of_stay_days"].mean())
print(df["length_of_stay_days"].median())

sns.countplot(data=df, x="department")
plt.title("Number of Patients by Department")
plt.xticks(rotation=45)
plt.show()

df["visit_type"].value_counts().plot(
   kind="pie",
   autopct="%1.1f%%"
)
plt.title("Emergency vs Routine Visits")
plt.ylabel("")
plt.show()

plt.hist(df["treatment_cost"], bins=20)
plt.title("Distribution of Treatment Cost")
plt.xlabel("Treatment Cost")
plt.ylabel("Number of Patients")
plt.show()

avg_cost = df.groupby("age_group")["treatment_cost"].mean()
plt.plot(avg_cost.index, avg_cost.values, marker="o")
plt.title("Average Treatment Cost by Age Group")
plt.xlabel("Age Group")
plt.ylabel("Average Treatment Cost")
plt.show()

print(df["treatment_cost"].mean())
print(df["treatment_cost"].median())
print(df["treatment_cost"].std())

print(
   df[["length_of_stay_days", "treatment_cost"]].corr()
)

sns.scatterplot(
   data=df,
   x="length_of_stay_days",
   y="treatment_cost"
)
plt.title("Hospital Stay vs Treatment Cost")
plt.show()

import plotly.express as px

fig = px.scatter(
    df,
    x="length_of_stay_days",
    y="treatment_cost",
    color="visit_type",
    title="Interactive Hospital Stay vs Treatment Cost",
    labels={
        "length_of_stay_days": "Length of Stay (Days)",
        "treatment_cost": "Treatment Cost (₹)",
        "visit_type": "Visit Type"
    }
)

fig.show()

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor


df = pd.read_csv("healthcare_patient_analytics.csv")

encoders = {}

columns = [
    "age_group",
    "gender",
    "department",
    "treatment_type",
    "visit_type"
]

for col in columns:
    encoders[col] = LabelEncoder()
    df[col] = encoders[col].fit_transform(df[col])


X_stay = df[
    [
        "age_group",
        "gender",
        "department",
        "treatment_type",
        "visit_type"
    ]
]

y_stay = df["length_of_stay_days"]

stay_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

stay_model.fit(X_stay, y_stay)


X_cost = df[
    [
        "age_group",
        "gender",
        "department",
        "treatment_type",
        "visit_type",
        "length_of_stay_days"
    ]
]

y_cost = df["treatment_cost"]

cost_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

cost_model.fit(X_cost, y_cost)



print("\n=== PATIENT DETAILS ===\n")

age = input(
    "Enter Age Group (18-30, 31-45, 46-60, 60+): "
)

gender = input(
    "Enter Gender (Male/Female): "
)

treatment = input(
    "Enter Treatment Type: "
)

department = input(
    "Enter Department: "
)

visit = input(
    "Enter Visit Type (Emergency/Routine): "
)


patient = pd.DataFrame({
    "age_group": [
        encoders["age_group"].transform([age])[0]
    ],

    "gender": [
        encoders["gender"].transform([gender])[0]
    ],

    "department": [
        encoders["department"].transform([department])[0]
    ],

    "treatment_type": [
        encoders["treatment_type"].transform([treatment])[0]
    ],

    "visit_type": [
        encoders["visit_type"].transform([visit])[0]
    ]
})


predicted_stay = stay_model.predict(patient)[0]

# Create minimum and maximum stay
min_stay = max(1, round(predicted_stay - 2))
max_stay = max(min_stay, round(predicted_stay + 2))



# Predict cost using predicted average stay
patient_base = patient.copy()

patient_base["length_of_stay_days"] = round(predicted_stay)

base_cost = cost_model.predict(patient_base)[0]



# Calculate average cost per hospital day
cost_per_day = df["treatment_cost"].sum() / df["length_of_stay_days"].sum()

# ==========================================
# 10. CALCULATE MINIMUM AND MAXIMUM COST
# ==========================================

# Keep base cost related to patient condition
# and adjust it according to stay duration.

min_cost = base_cost - (
    (predicted_stay - min_stay) * cost_per_day
)

max_cost = base_cost + (
    (max_stay - predicted_stay) * cost_per_day
)

# Make sure maximum cost is always >= minimum cost
if max_cost < min_cost:
    max_cost = min_cost



print("-- HEALTHCARE PREDICTION --")

print("\nPatient Details")
print("-------------------")

print("Age Group       :", age)
print("Gender          :", gender)
print("Treatment       :", treatment)
print("Department      :", department)
print("Visit Type      :", visit)

print("\n-- PREDICTION --")

print("\nMinimum Prediction")
print("Length of Stay  :", min_stay, "days")
print("Treatment Cost  : ₹", round(min_cost, 2))

print("\nMaximum Prediction")
print("Length of Stay  :", max_stay, "days")
print("Treatment Cost  : ₹", round(max_cost, 2))